### ISSUE TITLE
Issue starting Logstash

### ISSUE THREAD

**Issue by matthew-hickok** [spujadas/elkx-docker#11]
Hey, I'm using version 5.6 and this is what I have for my compose file: 

elkx:
  image: sebp/elkx:560
  ports:
    - "5601:5601"
    - "9200:9200"
    - "5044:5044"
  environment:
    - ES_JAVA_OPTS="Xms512m -Xmx2g"

About as simple as it can be and I'm not making any customizations. Then I just do a docker-compose up and everything seems to start up just fine. 

But when I try to create a dummy log by going this: 

/opt/logstash/bin/logstash -e 'input { stdin { } } output { elasticsearch { hosts => ["localhost"] user => "elastic" password => "changeme" } }'

I get the error: 

[FATAL][logstash.runner] Logstash could not be started because there is already another instance using the configured data directory.  If you wish to run multiple instances, you must change the "path.data" setting.

I definitely don't have multiple instances running. I don't even have any other containers running on this host. Any ideas? 

Thanks!

**Comment by matthew-hickok** [comment]
I figured it out. In the documentation, with regards to creating a dummy log it states: 

" ...use the following command instead of the original one:
# /opt/logstash/bin/logstash -e 'input { stdin { } } output { elasticsearch { hosts => ["localhost"] user => "elastic" password => "changeme" } }'
"

This does not work. It requires the data path to be explicitly defined: 

/opt/logstash/bin/logstash **--path.data /tmp/logstash/data** -e 'input { stdin { } } output { elasticsearch { hosts => ["localhost"] user => "elastic" password => "changeme" } }'

**Comment by spujadas** [comment]
You're absolutely right, I had added this option in the documentation for the sebp/elk image, but forgot to cascade it to sebp/elkx. Will update soon.
