### ISSUE TITLE
ERROR: Setting [bootstrap.pass] does not exist in the keystore.

### ISSUE THREAD

**Issue by Niondir** [spujadas/elkx-docker#19]
When starting in Bootstrap mode I get the following error (first line in log): `ERROR: Setting [bootstrap.pass] does not exist in the keystore.`

**Comment by spujadas** [comment]
Actually the normal (expected) behaviour of `elasticsearch-keystore`, which is cleaning the keystore by attempting to remove a possibly existing bootstrap password: when this password hasn't actually been set, an error message is displayed.
Will suppress the output to avoid confusion.
