### ISSUE TITLE
Seems like SIGTERM trap doesn’t work

### ISSUE THREAD

**Issue by exalted** [spujadas/elkx-docker#20]
When shutting down a container (i.e. `CTRL-c`) in https://github.com/spujadas/elk-docker, I can see…

```
_term() {
  echo "Terminating ELK"
  service elasticsearch stop
  service logstash stop
  service kibana stop
  exit 0
}
```

… executes, outputs “Terminating ELK” and stops services correctly.

This doesn’t seem to work in `elkx-docker` (here) however.

Maybe it is because `start.sh` (`CMD` for `elk-docker` image) executed internally from `startx.sh` (`CMD` for `elkx-docker` image)?

Thanks.

**Comment by spujadas** [comment]
Well spotted, should now be solved (build in progress), let me know if you're still experiencing this issue.

**Comment by exalted** [comment]
@spujadas thanks for fixing it, however don't you think it is sort of duplication in what's in `start.sh` already? Perhaps you may want to consider something like in `startx.sh` instead:

```bash
_term() { 
  kill -TERM "$child" 2>/dev/null
}

trap _term SIGTERM

/usr/local/bin/start.sh &

child=$! 
wait "$child"
```

^ Ref.: https://unix.stackexchange.com/questions/146756/forward-sigterm-to-child-in-bash

So `startx.sh` shouldn't really "know" how to kill what `start.sh` is starting, merely forward the term signal to it.

More good stuff in http://veithen.github.io/2014/11/16/sigterm-propagation.html as well.

What do you think?

**Comment by spujadas** [comment]
Clever and infinitely more elegant than my quick and dirty workaround, thanks!
Will implement your solution.

**Comment by spujadas** [comment]
Great stuff, just needed an extra `wait ${child}` in the `_term()` function otherwise `startx.sh` wouldn't wait until `start.sh` ended before exiting.
