### ISSUE TITLE
sebp/elkx with TLS ?

### ISSUE THREAD

**Issue by alnhk** [spujadas/elkx-docker#24]
With SEBP/ELKX two nodes container, applying the TLS using the provided instruction (6.2.4) https://www.elastic.co/guide/en/elasticsearch/reference/6.2/configuring-tls.html#node-certificates is failing. Is there any clear instruction to enable TLS on this SEBP/ELKX ?

**Comment by spujadas** [comment]
No plan to provide further instructions regarding the configuration and customisation of ELK(X), it's really up to the users to set up and tweak the image as they see fit, with help from e.g. http://discuss.elastic.co if needed.
(Unless there's an issue with the image itself, in which case I'll look into it.)

**Comment by alnhk** [comment]
Yeah, i followed this instruction in order to enable TLS on SEBP/ELKX and install the license (license will only work unless TLS is enabled), however with SEBP/ELKX, everything broke up and not accepting at all. Anyways - thanks for help.
