### ISSUE TITLE
Adding credentials...

### ISSUE THREAD

**Issue by shawnmmatthews** [spujadas/elkx-docker#7]
With regards to changing the passwords for the primary elastic user.

Could we simply add something like this to the dockerfile? In the correct format?

RUN curl -XPUT -u elastic 'localhost:9200/_xpack/security/user/elastic/_password' -H "Content-Type: application/json" -d '{
  "password" : "elasticpassword"
}'

I know you mentioned env variables as an option.

Ideally i'm trying to change the password and create a read only user during the build process.

Any thoughts on how to get started would be VERY appreciated. Thanks for the wonderful image.

Best,
Shawn

**Comment by spujadas** [comment]
I think the easiest way to go about this would be to add a post-hook shell script (see http://elk-docker.readthedocs.io/#pre-post-hooks) that runs the command you need once all the services are running.

(Adding a `RUN` directive in the `Dockerfile` wouldn't work as the command would be run at build time whilst the service isn't running, so it would fail.)

Also, thanks for the kind words!

**Comment by shawnmmatthews** [comment]
Awesome I think that puts me on the right path!

All the best.
Shawn

**Comment by shawnmmatthews** [comment]
Sorry to reopen, but thought you might be able to help on this @spujadas .

I added a file via
`ADD elk-post-hooks.sh /usr/local/bin/` (in the dockerfile)

ssh'd into the container after startup and sure enough its there.

Nothing seems to be executing from within it. 

I tried a simple `echo "Testing"` after my initial curl command didn't work, and nothing printed after the startup. Is there a way to test that things are being executed?

Also am I (very) potentially overcomplicating changing the password for the admin user, by trying to run a curl command from inside the shell script? Is there something easier I'm missing?

I really appreciate your time and patience.

**Comment by spujadas** [comment]
> Nothing seems to be executing from within it.
> 
> I tried a simple echo "Testing" after my initial curl command didn't work, and nothing printed after the startup. Is there a way to test that things are being executed?

Hmmm, should have worked. Two questions:

- Is your `.sh` file executable?

- Are you using `sebp/elkx:552` or later (see https://github.com/spujadas/elk-docker/issues/167#issuecomment-330615993 for a similar issue)

> Also am I (very) potentially overcomplicating changing the password for the admin user, by trying to run a curl command from inside the shell script? Is there something easier I'm missing?

Well the documentation from X-Pack seems to suggest that this is the way to go (goes through an HTTP request, which implies using something like cURL, and a shell script would make sense to automate this), but I'm not an ELK expert myself so I'd suggest asking for advice over at https://discuss.elastic.co/c/x-pack

**Comment by shawnmmatthews** [comment]
Thanks for getting back to me.

Super interesting... 

Upon making the script executable the scripts appear to be running. I setup a `elk-pre-hook.sh` with `echo "Testing"` and it correctly returned as soon as  the container started up. In case anyone stumbles across this I did this by adding `RUN chmod +x /usr/local/bin/elk-pre-hooks.sh` after the `ADD elk-pre-hooks.sh /usr/local/bin/` in my dockerfile.

However as soon as I add `elk-post-hook.sh` and make it executable Kibana fails to start even if all that is in the file is `echo "Post Testing"` Any thoughts? I attached the log, but having read it nothing to me looks out of order.

For the record I'm running `sebp/elkx:561`.

`{"type":"log","@timestamp":"2017-09-29T16:42:04Z","tags":["status","plugin:kibana@5.6.1","info"],"pid":192,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2017-09-29T16:42:04Z","tags":["status","plugin:elasticsearch@5.6.1","info"],"pid":192,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2017-09-29T16:42:04Z","tags":["status","plugin:xpack_main@5.6.1","info"],"pid":192,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2017-09-29T16:42:04Z","tags":["status","plugin:graph@5.6.1","info"],"pid":192,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2017-09-29T16:42:04Z","tags":["status","plugin:monitoring@5.6.1","info"],"pid":192,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2017-09-29T16:42:04Z","tags":["reporting","warning"],"pid":192,"message":"Generating a random key for xpack.reporting.encryptionKey. To prevent pending reports from failing on restart, please set xpack.reporting.encryptionKey in kibana.yml"}
{"type":"log","@timestamp":"2017-09-29T16:42:04Z","tags":["status","plugin:reporting@5.6.1","info"],"pid":192,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2017-09-29T16:42:10Z","tags":["status","plugin:xpack_main@5.6.1","info"],"pid":192,"state":"yellow","message":"Status changed from yellow to yellow - No existing Kibana index found","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
{"type":"log","@timestamp":"2017-09-29T16:42:10Z","tags":["status","plugin:graph@5.6.1","info"],"pid":192,"state":"yellow","message":"Status changed from yellow to yellow - No existing Kibana index found","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
{"type":"log","@timestamp":"2017-09-29T16:42:10Z","tags":["status","plugin:reporting@5.6.1","info"],"pid":192,"state":"yellow","message":"Status changed from yellow to yellow - No existing Kibana index found","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
{"type":"log","@timestamp":"2017-09-29T16:42:10Z","tags":["status","plugin:elasticsearch@5.6.1","info"],"pid":192,"state":"yellow","message":"Status changed from yellow to yellow - No existing Kibana index found","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
{"type":"log","@timestamp":"2017-09-29T16:42:11Z","tags":["status","plugin:elasticsearch@5.6.1","info"],"pid":192,"state":"green","message":"Status changed from yellow to green - Kibana index ready","prevState":"yellow","prevMsg":"No existing Kibana index found"}
{"type":"log","@timestamp":"2017-09-29T16:42:11Z","tags":["license","info","xpack"],"pid":192,"message":"Imported license information from Elasticsearch for [data] cluster: mode: trial | status: active | expiry date: 2017-10-29T16:41:52+00:00"}
{"type":"log","@timestamp":"2017-09-29T16:42:11Z","tags":["status","plugin:xpack_main@5.6.1","info"],"pid":192,"state":"green","message":"Status changed from yellow to green - Ready","prevState":"yellow","prevMsg":"No existing Kibana index found"}
{"type":"log","@timestamp":"2017-09-29T16:42:11Z","tags":["status","plugin:graph@5.6.1","info"],"pid":192,"state":"green","message":"Status changed from yellow to green - Ready","prevState":"yellow","prevMsg":"No existing Kibana index found"}
{"type":"log","@timestamp":"2017-09-29T16:42:11Z","tags":["status","plugin:reporting@5.6.1","info"],"pid":192,"state":"green","message":"Status changed from yellow to green - Ready","prevState":"yellow","prevMsg":"No existing Kibana index found"}
{"type":"log","@timestamp":"2017-09-29T16:42:11Z","tags":["status","plugin:monitoring@5.6.1","info"],"pid":192,"state":"yellow","message":"Status changed from green to yellow - Waiting for Monitoring Health Check","prevState":"green","prevMsg":"Ready"}
{"type":"log","@timestamp":"2017-09-29T16:42:12Z","tags":["status","plugin:monitoring@5.6.1","info"],"pid":192,"state":"green","message":"Status changed from yellow to green - Ready","prevState":"yellow","prevMsg":"Waiting for Monitoring Health Check"}
{"type":"log","@timestamp":"2017-09-29T16:42:18Z","tags":["status","plugin:security@5.6.1","info"],"pid":192,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2017-09-29T16:42:18Z","tags":["security","warning"],"pid":192,"message":"Generating a random key for xpack.security.encryptionKey. To prevent sessions from being invalidated on restart, please set xpack.security.encryptionKey in kibana.yml"}
{"type":"log","@timestamp":"2017-09-29T16:42:18Z","tags":["security","warning"],"pid":192,"message":"Session cookies will be transmitted over insecure connections. This is not recommended."}
{"type":"log","@timestamp":"2017-09-29T16:42:18Z","tags":["status","plugin:searchprofiler@5.6.1","info"],"pid":192,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2017-09-29T16:42:18Z","tags":["status","plugin:ml@5.6.1","info"],"pid":192,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2017-09-29T16:42:18Z","tags":["status","plugin:ml@5.6.1","info"],"pid":192,"state":"yellow","message":"Status changed from green to yellow - Waiting for Elasticsearch","prevState":"green","prevMsg":"Ready"}
{"type":"log","@timestamp":"2017-09-29T16:42:18Z","tags":["status","plugin:ml@5.6.1","info"],"pid":192,"state":"green","message":"Status changed from yellow to green - Ready","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
{"type":"log","@timestamp":"2017-09-29T16:42:18Z","tags":["status","plugin:tilemap@5.6.1","info"],"pid":192,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2017-09-29T16:42:18Z","tags":["status","plugin:watcher@5.6.1","info"],"pid":192,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2017-09-29T16:42:18Z","tags":["status","plugin:grokdebugger@5.6.1","info"],"pid":192,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2017-09-29T16:42:18Z","tags":["status","plugin:upgrade@5.6.1","info"],"pid":192,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2017-09-29T16:42:18Z","tags":["status","plugin:console@5.6.1","info"],"pid":192,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2017-09-29T16:42:18Z","tags":["status","plugin:metrics@5.6.1","info"],"pid":192,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2017-09-29T16:42:19Z","tags":["status","plugin:timelion@5.6.1","info"],"pid":192,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2017-09-29T16:42:19Z","tags":["listening","info"],"pid":192,"message":"Server running at http://0.0.0.0:5601"}
{"type":"log","@timestamp":"2017-09-29T16:42:19Z","tags":["status","ui settings","info"],"pid":192,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"response","@timestamp":"2017-09-29T16:42:19Z","tags":[],"pid":192,"method":"get","statusCode":302,"req":{"url":"/","method":"get","headers":{"host":"localhost:5601","user-agent":"curl/7.47.0","accept":"*/*"},"remoteAddress":"127.0.0.1","userAgent":"127.0.0.1"},"res":{"statusCode":302,"responseTime":36,"contentLength":9},"message":"GET / 302 36ms - 9.0B"}
{"type":"response","@timestamp":"2017-09-29T16:42:20Z","tags":[],"pid":192,"method":"get","statusCode":302,"req":{"url":"/","method":"get","headers":{"host":"localhost:5601","user-agent":"curl/7.47.0","accept":"*/*"},"remoteAddress":"127.0.0.1","userAgent":"127.0.0.1"},"res":{"statusCode":302,"responseTime":18,"contentLength":9},"message":"GET / 302 18ms - 9.0B"}
{"type":"response","@timestamp":"2017-09-29T16:42:21Z","tags":[],"pid":192,"method":"get","statusCode":302,"req":{"url":"/","method":"get","headers":{"host":"localhost:5601","user-agent":"curl/7.47.0","accept":"*/*"},"remoteAddress":"127.0.0.1","userAgent":"127.0.0.1"},"res":{"statusCode":302,"responseTime":4,"contentLength":9},"message":"GET / 302 4ms - 9.0B"}
{"type":"response","@timestamp":"2017-09-29T16:42:22Z","tags":[],"pid":192,"method":"get","statusCode":302,"req":{"url":"/","method":"get","headers":{"host":"localhost:5601","user-agent":"curl/7.47.0","accept":"*/*"},"remoteAddress":"127.0.0.1","userAgent":"127.0.0.1"},"res":{"statusCode":302,"responseTime":4,"contentLength":9},"message":"GET / 302 4ms - 9.0B"}
{"type":"response","@timestamp":"2017-09-29T16:42:23Z","tags":[],"pid":192,"method":"get","statusCode":302,"req":{"url":"/","method":"get","headers":{"host":"localhost:5601","user-agent":"curl/7.47.0","accept":"*/*"},"remoteAddress":"127.0.0.1","userAgent":"127.0.0.1"},"res":{"statusCode":302,"responseTime":3,"contentLength":9},"message":"GET / 302 3ms - 9.0B"}
{"type":"response","@timestamp":"2017-09-29T16:42:24Z","tags":[],"pid":192,"method":"get","statusCode":302,"req":{"url":"/","method":"get","headers":{"host":"localhost:5601","user-agent":"curl/7.47.0","accept":"*/*"},"remoteAddress":"127.0.0.1","userAgent":"127.0.0.1"},"res":{"statusCode":302,"responseTime":3,"contentLength":9},"message":"GET / 302 3ms - 9.0B"}
{"type":"response","@timestamp":"2017-09-29T16:42:24Z","tags":[],"pid":192,"method":"get","statusCode":302,"req":{"url":"/","method":"get","headers":{"host":"localhost:5601","user-agent":"curl/7.47.0","accept":"*/*"},"remoteAddress":"127.0.0.1","userAgent":"127.0.0.1"},"res":{"statusCode":302,"responseTime":3,"contentLength":9},"message":"GET / 302 3ms - 9.0B"}`

**Comment by shawnmmatthews** [comment]
... does it make sense to just try running the following 

`## run post-hooks
if [ -x /usr/local/bin/elk-post-hooks.sh ]; then
  ### if Kibana was started...
  if [ "$KIBANA_START" -eq "1" ]; then

  ### ... then wait for Kibana to be up first to ensure that .kibana index is
  ### created before the of post-hooks are executed
    # set number of retries (default: 30, override using KIBANA_CONNECT_RETRY env var)
    if ! [[ $KIBANA_CONNECT_RETRY =~ $re_is_numeric ]] ; then
       KIBANA_CONNECT_RETRY=30
    fi

    counter=0
    while [ ! "$(curl localhost:5601 2> /dev/null)" -a $counter -lt $KIBANA_CONNECT_RETRY  ]; do
      sleep 1
      ((counter++))
      echo "waiting for Kibana to be up ($counter/$KIBANA_CONNECT_RETRY)"
    done
    if [ ! "$(curl localhost:5601 2> /dev/null)" ]; then
      echo "Couln't start Kibana. Exiting."
      echo "Kibana log follows below."
      cat /var/log/kibana/kibana5.log
      exit 1
    fi
  fi

  . /usr/local/bin/elk-post-hooks.sh
fi`

as

`## run pre-hooks
if [ -x /usr/local/bin/elk-pre-hooks.sh ]; then
  . /usr/local/bin/elk-pre-hooks.sh
fi`

**Comment by spujadas** [comment]
> However as soon as I add elk-post-hook.sh and make it executable Kibana fails to start even if all that is in the file is echo "Post Testing" Any thoughts? I attached the log, but having read it nothing to me looks out of order.

Very strange indeed, the logs show Kibana starting up normally, so perhaps it needs the `curl` loop in `start.sh` to wait longer so that Kibana finishes initialising. Could you bump up the `KIBANA_CONNECT_RETRY` env var to a high value (1000 or something)?

> ... does it make sense to just try running the following...

For the purposes of just testing `echo` you could, but if you attempt to run the `curl` command that changes the primary user it will definitely fail because Kibana won't be up (hence the loop in `start.sh` that waits long enough for Kibana to be up and running). Hope that makes sense.

**Comment by shawnmmatthews** [comment]
It fails all the way to 1000. I'm trying to think up ways to rewrite the test to see if Kabana is up. Kabana is up successfully before the test, but the test fails to hit it and confirm.

Luckily for me you can reset the ES passwords via sheild without Kibana up so changing the passwords is easy enough via curl. Same with adding users and mapping which are the steps I really needed to automate.

Thanks for your help @spujadas. I will let you know if I come up with a solution. For right now I'm running a modified shell.sh that replaces the post command with the same one as the pre. It allows for curl on ES but not on Kibana or Log.

**Comment by spujadas** [comment]
Thanks for the feedback, much appreciated.

I'll try and perform some more tests on my end to attempt to reproduce as this is most unusual. It appears that something is wrong with the way the script tests if Kibana is up (probably user permissions, haven't tested the post-hooks with ELKX, just with ELK).

(Oh, I realise that I got the services mixed up in my previous comment, your `curl` command would actually – and quite obviously! – work in `elk-post-hooks.sh` as you're sending a request to ES, which is meant to be up and running before Logstash and Kibana are started, and would therefore be up before the post-hooks script is started.)

**Comment by spujadas** [comment]
Reproduced the issue, was due to the loop testing if Kibana is up needing curl to provide a login and password with XPack => should now be working properly, but may need `KIBANA_CONNECT_RETRY` to be bumped up (needs 28 iterations on my set-up, which is too close to the 30 iteration cutoff for comfort).
Is now corrected in tag `562`.

**Comment by shawnmmatthews** [comment]
Thanks @spujadas I'll do some testing this morning.
